### ISSUE TITLE
Add lots of links to sources in "Integrations" subsection

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#10]

**Comment by knodel** [comment]
And now with references at every item:

![Screen Shot 2022-01-18 at 15 28 57](https://user-images.githubusercontent.com/18582732/149956533-a2ce40fc-0143-4d7f-8dd7-b324097a55aa.png)

**Comment by poikilotherm** [comment]
I changed a fit bits. @juckel and @sdruskat please continue reviewing :smile:

**Comment by sdruskat** [comment]
Went and fixed a few more things. Closing.
