### ISSUE TITLE
Add RSD workflow to table and in text

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/concept-paper#11]
The workflow is relevant and should be described.

- [X] Table
- [x] Text

**Comment by poikilotherm** [comment]
![image](https://user-images.githubusercontent.com/5468333/149182641-d3ea6f97-df91-466a-885d-ffcf4f626566.png)

**Comment by poikilotherm** [comment]
@sdruskat please review the table entry. Thx.

**Comment by poikilotherm** [comment]
Also added some text in refactored pull workflows paragraph.

![image](https://user-images.githubusercontent.com/5468333/149363163-fa07ce97-3ce6-454b-8c97-6f1bf49b4c17.png)

Taking me of this ticket and assigning to you lot @hermes-hmc for review.

**Comment by juckel** [comment]
done
