### ISSUE TITLE
Discuss adding hint on community feedback to route to this repository (for issues&/PRs)

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#15]
In addition to link to website or as a replacement?

**Comment by poikilotherm** [comment]
@knodel and @poikilotherm discussed: let's provide a more related link to this project to leave feedback on the paper instead of our generic web page.

**Comment by juckel** [comment]
@poikilotherm would implicitly mentioning creating issues as a feedback channel be useful? Or do we on purpose leave it open so the full pull requests etc. can be submitted as well? I am wondering if we are raising the bar too high for someone who has never worked with GitHub before... Or is this not really an issue with our target audience?

**Comment by poikilotherm** [comment]
I'm fine with making this more concrete. WDYT @knodel @sdruskat

**Comment by sdruskat** [comment]
Using PuPeer via a redirect from http://software-metadata.pub/concept-paper-community-reviews.
