### ISSUE TITLE
Discuss changing the title

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#16]
`title`: "HERMES: A concept for automated workflows for software publication with rich metadata"

changing to `title`: "Concept for HERMES", `subtitle`: "Automated workflows for software publication with rich metadata"

**Comment by poikilotherm** [comment]
Allows reusing the shorter title within the footer and PDF metadata

**Comment by poikilotherm** [comment]
After discussion with @knodel, changed to "Rich Metadata Software Publications: HERMES' concept for an automated workflow"

**Comment by juckel** [comment]
👍

**Comment by poikilotherm** [comment]
Currently we wrote ~10 text pages + 2 tables for covering state of the art. Our actual concept is 3 text pages + 2 pictures. (#12 is related here).

After re-thinking: should we add sth. to the subtitle to represent this majority of our paper?

**Comment by sdruskat** [comment]
Changed title to "Software publications with rich metadata" for readability.

**Comment by sdruskat** [comment]
Subtitle changed to "State of the art and HERMES’ concept for automated workflows".

**Comment by sdruskat** [comment]
Now:

> ### Software publications with rich metadata
> #### State of the art, automated workflows and HERMES concep
