### ISSUE TITLE
Elaborate on the origin of table 1 (metadata mapping)

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#18]
A comment by Bernhard Mittermaier on: "Table 1 on page X shows a mapping of metadata types to the formats they are commonly provided in." (Originating from #12)

> It would be interesting to learn a little more about the way this mapping was compiled, e.g: what was the criterion für "commonly"?

@sdruskat please consider adding some details within the section or in the table description. Thx!
(Also marked as comment in Overleaf)

**Comment by sdruskat** [comment]
Done.
