### ISSUE TITLE
Add hints about source order / precedence

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#2]
Example: https://git.opencarp.org/openCARP/openCARP/-/tree/master What should a pipeline do with this?

Leave this open enough for implementation phase degrees of freedom, but at least note that we thought about this aspect.

**Comment by sdruskat** [comment]
Added (in what is currently l. 522):

> In cases where several instances of structured metadata sources exist and contain overlapping -- and potentially diverging -- information, we follow a set of heuristics to establish source precedence, and avoid conflicts in a defensive manner.

**Comment by poikilotherm** [comment]
![image](https://user-images.githubusercontent.com/5468333/149536620-8673f3e2-76d3-4bc4-9781-74b9b62a4111.png)

**Comment by poikilotherm** [comment]
The TODO had been added to section "3.4.2 Expectations on users" before:

![image](https://user-images.githubusercontent.com/5468333/149556180-60dac1d1-8311-444d-a7d5-382e5f45d994.png)

Should we add a cross link or maybe even some redundant text?

**Comment by poikilotherm** [comment]
@knodel says this is fine.
