### ISSUE TITLE
PubPeer #5: Any possibility to differentiate between software application and software source code?

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#21]
https://pubpeer.com/publications/43D31C250F3EC89D2AB6464FDD51E1#5

Someone anonymously asked: "any possibility to differentiate between software application and software source code?"

Ideas to extend the paper as follows:
- --> Scope --> In Scope (3.4.3) describes very well our differentiated approach but is hidden to a fast reader
- Add sth. about artificats in abstract (distinguish more publication, metadata and artifacts)
- Add sth. about artifacts/sourcecode/... in second paragraph of Introduction to make it more clear to the reader

Make it a pretty reply - maybe this is still not enough differentiation.

**Comment by sdruskat** [comment]
Preparing an answer in https://pad.gwdg.de/1-cYeRqfRV-Bfob_F8Gy6g#

**Comment by sdruskat** [comment]
Answered in https://pubpeer.com/publications/43D31C250F3EC89D2AB6464FDD51E1#8.
