### ISSUE TITLE
Adapt diagrams for LaTeX

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#3]
Include as SVG or similar, make it look pretty. Same font would be a bonus :smile: 

Image sources (PlantUML) here: https://github.com/hermes-hmc/concept-paper/tree/main/images
PlantUML + Docker: https://www.oscarberg.com/blog/plantuml-docker/

**Comment by poikilotherm** [comment]
- Could not make it work with TiKZ, as layout and C4 images etc are missing.
- Could not make it work with SVG, as the necessary conversion from SVG to PDF via Inkscape (done by `\usepackage{svg}`) fails with some rogue math symbols.
- Included PlantUML -> SVG Export -> Inkscape PDF Export via `\includegraphics`. Not perfect in terms of layout, fonts and size, but works.
- Moved to "Tables and Figures" section to avoid two huge image pages between tiny text parts.

**Comment by poikilotherm** [comment]
Please review at all (missing on geometry thing still todo as with #6

**Comment by poikilotherm** [comment]
Geometry done :smile:

**Comment by juckel** [comment]
looks good
