### ISSUE TITLE
Add Dataverse Uploader Github Action to Workflows

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#4]

**Comment by poikilotherm** [comment]
Done.

![image](https://user-images.githubusercontent.com/5468333/149973718-277ac3a8-ff1c-486f-a538-972c3891bf8c.png)

@hermes-hmc please review :smile:

**Comment by atrisovic** [comment]
Can I make modifications to this? I'd like to add a CFF file to the repo, move it to IQSS (instad of atrisovic) and review the paragraph.

**Comment by poikilotherm** [comment]
Sure, go ahead @atrisovic :smile: You could also move it to @gdcc :wink: 
(You know about https://citation-file-format.github.io/cff-initializer-javascript to have an easier thing to start with, don't you?)

Leave a note when you're done, I'll update the reference then. And thx for reaching out! :+1:

**Comment by atrisovic** [comment]
Where is this paragraph? I can't find it in the main tex file, but I'd like to see it in the context.

**Comment by sdruskat** [comment]
Hi @atrisovic, just invited you to the Overleaf with edit rights.

**Comment by atrisovic** [comment]
Thanks! I updated the paragraph. Please have a look and feel free to make modifications :))

**Comment by poikilotherm** [comment]
Compressed the paragraph to fit the length of others and the page. Done.
