### ISSUE TITLE
Investigate creating a merged table for push & pull workflows

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#6]
Instead of two tables, make things easier to compare.
Enhance with more details about supported metadata, targets etc.

**Comment by poikilotherm** [comment]
The table is done for now, with one small exception: the page geometry should be changed to make it fit and centered. (Left a visible TODO for that) Dear all: please review (together with #11).

(Please unassign yourself from this issue if you reviewed and left comments/edits)

**Comment by juckel** [comment]
Looks great
