### ISSUE TITLE
Bibtex: switch software citations to biblatex-software types

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/concept-paper#8]
http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-software/software-biblatex.pdf

**Comment by sdruskat** [comment]
I'll do this. Was wanting to test-drive biblatex-software for a good long time now.

**Comment by poikilotherm** [comment]
Nice. I already added some examples for new references I have been adding during refactoring of the tables #2

**Comment by poikilotherm** [comment]
Taking over here @sdruskat :heart_decoration:

**Comment by poikilotherm** [comment]
Done
